[package]
name = "prjcombine_virtex6_rd2db"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_rdintb.workspace = true
prjcombine_rdgrid.workspace = true
prjcombine_rawdump.workspace = true
prjcombine_virtex4.workspace = true
