[package]
name = "prjcombine_hammer"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_entity.workspace = true
serde.workspace = true
bitvec.workspace = true
bimap.workspace = true
rand.workspace = true
std-semaphore.workspace = true
