[package]
name = "prjcombine_xc4k"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
serde.workspace = true

[lints]
workspace = true
