[package]
name = "prjcombine"
version = "0.1.0"
authors = ["Marcelina Kościelnicka <mwk@0x04.net>"]
edition = "2018"

[dependencies]
tempdir = "0.3.7"
nix = "0.22.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
toml = "0.5"
zstd = "0.9"
rayon = "1.5"
jemallocator = "0.3.0"
itertools = "0.10"
structopt = "0.3"
ndarray = { version = "0.15", features = ["serde", "rayon"] }
indexmap = "1.7"
