[workspace]

members = [
	"prjcombine_entity",
	"prjcombine_toolchain",
	"prjcombine_rawdump",
	"prjcombine_rdbuild",
	"prjcombine_ise_dump",
	"prjcombine_vivado_dump",
	"prjcombine_xilinx_rd2geom",
	"prjcombine_xilinx_geom",
	"prjcombine_xdl",
	"prjcombine_v2xdl_verify",
]

[profile.release]
debug = 2
