[workspace]

members = [
	"prjcombine_entity",
	"prjcombine_toolchain",
	"prjcombine_rawdump",
	"prjcombine_rdbuild",
	"prjcombine_ise_dump",
	"prjcombine_vivado_dump",
	"prjcombine_int",
	"prjcombine_xc4k",
	"prjcombine_xc5200",
	"prjcombine_virtex",
	"prjcombine_virtex2",
	"prjcombine_spartan6",
	"prjcombine_virtex4",
	"prjcombine_virtex5",
	"prjcombine_virtex6",
	"prjcombine_series7",
	"prjcombine_ultrascale",
	"prjcombine_versal",
	"prjcombine_rdgrid",
	"prjcombine_rdintb",
	"prjcombine_rdverify",
	"prjcombine_xc5200_rdverify",
	"prjcombine_virtex_rdverify",
	"prjcombine_virtex2_rdverify",
	"prjcombine_spartan6_rdverify",
	"prjcombine_virtex4_rdverify",
	"prjcombine_virtex5_rdverify",
	"prjcombine_virtex6_rdverify",
	"prjcombine_series7_rdverify",
	"prjcombine_ultrascale_rdverify",
	"prjcombine_versal_rdverify",
	"prjcombine_xc4k_rd2db",
	"prjcombine_xc5200_rd2db",
	"prjcombine_virtex_rd2db",
	"prjcombine_virtex2_rd2db",
	"prjcombine_spartan6_rd2db",
	"prjcombine_virtex4_rd2db",
	"prjcombine_virtex5_rd2db",
	"prjcombine_virtex6_rd2db",
	"prjcombine_series7_rd2db",
	"prjcombine_ultrascale_rd2db",
	"prjcombine_versal_rd2db",
	"prjcombine_xilinx_geom",
	"prjcombine_xilinx_rd2geom",
	"prjcombine_xdl",
	"prjcombine_v2xdl_verify",
]

[profile.dev]
opt-level = 2
debug = 2
