[package]
name = "prjcombine"
version = "0.1.0"
authors = ["Marcelina Kościelnicka <mwk@0x04.net>"]
edition = "2018"

[dependencies]
tempdir = "0.3.7"
nix = "0.17.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
toml = "0.5"
xz2 = "0.1"
rayon = "1.5"
