[package]
name = "prjcombine_xc5200"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
serde.workspace = true

[lints]
workspace = true
