[package]
name = "prjcombine_xc2000"
edition.workspace = true
version.workspace = true

[dependencies]
itertools.workspace = true
zstd.workspace = true
bincode.workspace = true
serde_json.workspace = true
unnamed_entity.workspace = true
prjcombine_types.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
serde.workspace = true

[lints]
workspace = true
