[package]
name = "prjcombine_ultrascale"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
serde.workspace = true
enum-map.workspace = true
bimap.workspace = true

[lints]
workspace = true
