[package]
name = "prjcombine_int"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
serde.workspace = true
enum-map.workspace = true
ndarray.workspace = true
bimap.workspace = true
[lints]
workspace = true
