[package]
name = "prjcombine_virtex"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
