[package]
name = "prjcombine_virtex4"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
assert_matches.workspace = true
serde.workspace = true
bimap.workspace = true
