[package]
name = "prjcombine_xdl"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_toolchain.workspace = true
tempfile.workspace = true
arrayref.workspace = true

[dev-dependencies]
clap.workspace = true

[lints]
workspace = true
