[package]
name = "prjcombine_xc4000_xact"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_xact_naming.workspace = true
prjcombine_xc4000.workspace = true

[lints]
workspace = true
