[package]
name = "prjcombine_xact_naming"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
unnamed_entity.workspace = true
prjcombine_int.workspace = true

[lints]
workspace = true
