[package]
name = "prjcombine_vivado_dump"
version = "0.1.0"
edition = "2021"

[dependencies]
prjcombine_xilinx_rawdump = { path = "../prjcombine_xilinx_rawdump" }
prjcombine_toolchain = { path = "../prjcombine_toolchain" }
prjcombine_entity = { path = "../prjcombine_entity" }
serde = { version = "1", features = ["derive"] }
simple-error = "0.2"
indexmap = "1.7"
rayon = "1.5"
structopt = "0.3"
indicatif = "0.16.2"
