[package]
name = "prjcombine_vivado_dump"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_rawdump.workspace = true
prjcombine_rdbuild.workspace = true
prjcombine_toolchain.workspace = true
prjcombine_entity.workspace = true
serde.workspace = true
simple-error.workspace = true
indexmap.workspace = true
rayon.workspace = true
clap.workspace = true
indicatif.workspace = true
