[package]
name = "prjcombine_versal"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
prjcombine_entity.workspace = true
prjcombine_int.workspace = true
enum-map.workspace = true
