[package]
name = "prjcombine_xc5200_xact"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_xact_naming.workspace = true
prjcombine_xc5200.workspace = true

[lints]
workspace = true
