[package]
name = "prjcombine_rawdump"
version = "0.1.0"
edition = "2021"

[dependencies]
prjcombine_entity = { path = "../prjcombine_entity" }
zstd = "0.9"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
structopt = "0.3"
ndarray = "0.15"
itertools = "0.10"
