[package]
name = "prjcombine_rawdump"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_entity.workspace = true
zstd.workspace = true
serde.workspace = true
bincode.workspace = true
clap.workspace = true
ndarray.workspace = true
itertools.workspace = true
