[package]
name = "prjcombine_xc4k_rd2db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prjcombine_entity = { path = "../prjcombine_entity" }
prjcombine_rdgrid = { path = "../prjcombine_rdgrid" }
prjcombine_rawdump = { path = "../prjcombine_rawdump" }
prjcombine_xc4k = { path = "../prjcombine_xc4k" }
