[package]
name = "prjcombine_types"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
bitvec.workspace = true
itertools.workspace = true
unnamed_entity.workspace = true

[lints]
workspace = true
