[package]
name = "prjcombine_rdgrid"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_rawdump.workspace = true
