[package]
name = "prjcombine_xilinx_geom"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
prjcombine_xc4k.workspace = true
prjcombine_xc5200.workspace = true
prjcombine_virtex.workspace = true
prjcombine_virtex2.workspace = true
prjcombine_spartan6.workspace = true
prjcombine_virtex4.workspace = true
prjcombine_ultrascale.workspace = true
prjcombine_versal.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
clap.workspace = true
rayon.workspace = true

[lints]
workspace = true
