[package]
name = "prjcombine_xilinx_geom"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_types.workspace = true
prjcombine_int.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine_virtex_bitstream.workspace = true
prjcombine_xc4000.workspace = true
prjcombine_xc4000_naming.workspace = true
prjcombine_xc5200.workspace = true
prjcombine_xc5200_naming.workspace = true
prjcombine_virtex.workspace = true
prjcombine_virtex_naming.workspace = true
prjcombine_virtex2.workspace = true
prjcombine_virtex2_naming.workspace = true
prjcombine_spartan6.workspace = true
prjcombine_spartan6_naming.workspace = true
prjcombine_virtex4.workspace = true
prjcombine_virtex4_naming.workspace = true
prjcombine_ultrascale.workspace = true
prjcombine_ultrascale_naming.workspace = true
prjcombine_versal.workspace = true
prjcombine_versal_naming.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
clap.workspace = true
rayon.workspace = true
itertools.workspace = true

[lints]
workspace = true
