[package]
name = "prjcombine_virtex5"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
assert_matches.workspace = true
prjcombine_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
prjcombine_virtex4.workspace = true
