[package]
name = "prjcombine_xilinx_rd2geom"
version = "0.1.0"
edition = "2021"

[dependencies]
prjcombine_entity = { path = "../prjcombine_entity" }
prjcombine_xilinx_geom = { path = "../prjcombine_xilinx_geom" }
prjcombine_xilinx_rawdump = { path = "../prjcombine_xilinx_rawdump" }
structopt = "0.3"
simple-error = "0.2"
serde = { version = "1.0", features = ["derive"] }
ron = "0.7"
rayon = "1.5.1"
enum-map = { version = "2.4.0", features = ["serde"] }
