[package]
name = "prjcombine_xilinx_recpld"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_entity.workspace = true
prjcombine_vm6.workspace = true
prjcombine_ise_dump.workspace = true
clap.workspace = true
prjcombine_toolchain.workspace = true
tempfile.workspace = true
simple-error.workspace = true
itertools.workspace = true
prjcombine_xilinx_cpld.workspace = true
prjcombine_rawdump.workspace = true
bitvec.workspace = true
prjcombine_hammer.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
enum-map.workspace = true
prjcombine_sdf.workspace = true
