[package]
name = "prjcombine_rdbuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prjcombine_rawdump = { path = "../prjcombine_rawdump" }
prjcombine_entity = { path = "../prjcombine_entity" }
