[package]
name = "prjcombine_xact_geom"
edition.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
zstd.workspace = true
bincode.workspace = true
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_virtex_bitstream.workspace = true
prjcombine_xc2000.workspace = true
prjcombine_xc2000_xact.workspace = true
prjcombine_xc4000.workspace = true
prjcombine_xc4000_xact.workspace = true
prjcombine_xc5200.workspace = true
prjcombine_xc5200_xact.workspace = true
prjcombine_xact_naming.workspace = true

[lints]
workspace = true
