[package]
name = "prjcombine_rdverify"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_rawdump.workspace = true
bitvec.workspace = true
