[package]
name = "prjcombine_xc2c"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
unnamed_entity.workspace = true
prjcombine_types.workspace = true

[lints]
workspace = true
