[package]
name = "prjcombine_rdintb"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_rawdump.workspace = true
assert_matches.workspace = true
enum-map.workspace = true
