[package]
name = "prjcombine_xc4000_rd2db"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_rdintb.workspace = true
prjcombine_rdgrid.workspace = true
prjcombine_rawdump.workspace = true
prjcombine_xc4000.workspace = true
enum-map.workspace = true

[lints]
workspace = true
